Detect libhackrf and libfftw

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5686,6 +5686,142 @@ fi
 done
 
 
+HAVE_LIBHACKRF=0
+HAVE_LIBFFTW3=0
+HAVE_HACKRF_H=0
+HAVE_FFTW3_H=0
+BUILD_HACKRF_SWEEP=0
+
+for ac_header in libhackrf/hackrf.h
+do :
+  ac_fn_cxx_check_header_mongrel "$LINENO" "libhackrf/hackrf.h" "ac_cv_header_libhackrf_hackrf_h" "$ac_includes_default"
+if test "x$ac_cv_header_libhackrf_hackrf_h" = xyes; then :
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBHACKRF_HACKRF_H 1
+_ACEOF
+ HAVE_HACKRF_H=1
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: \"Missing hackrf.h from libhackrf\"" >&5
+$as_echo "$as_me: WARNING: \"Missing hackrf.h from libhackrf\"" >&2;}
+fi
+
+done
+
+for ac_header in fftw3.h
+do :
+  ac_fn_cxx_check_header_mongrel "$LINENO" "fftw3.h" "ac_cv_header_fftw3_h" "$ac_includes_default"
+if test "x$ac_cv_header_fftw3_h" = xyes; then :
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_FFTW3_H 1
+_ACEOF
+ HAVE_FFTW3_H=1
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: \"Missing fftw3.h from libfftw\"" >&5
+$as_echo "$as_me: WARNING: \"Missing fftw3.h from libfftw\"" >&2;}
+fi
+
+done
+
+
+if test "$HAVE_HACKRF_H" -eq 1; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for hackrf_init in -lhackrf" >&5
+$as_echo_n "checking for hackrf_init in -lhackrf... " >&6; }
+if ${ac_cv_lib_hackrf_hackrf_init+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lhackrf  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char hackrf_init ();
+int
+main ()
+{
+return hackrf_init ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_link "$LINENO"; then :
+  ac_cv_lib_hackrf_hackrf_init=yes
+else
+  ac_cv_lib_hackrf_hackrf_init=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_hackrf_hackrf_init" >&5
+$as_echo "$ac_cv_lib_hackrf_hackrf_init" >&6; }
+if test "x$ac_cv_lib_hackrf_hackrf_init" = xyes; then :
+  HAVE_LIBHACKRF=1
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: libhackrf not available" >&5
+$as_echo "$as_me: WARNING: libhackrf not available" >&2;}
+fi
+
+fi
+
+if test "$HAVE_FFTW3_H" -eq 1; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for ffwtf_malloc in -lfftw3" >&5
+$as_echo_n "checking for ffwtf_malloc in -lfftw3... " >&6; }
+if ${ac_cv_lib_fftw3_ffwtf_malloc+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lfftw3  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char ffwtf_malloc ();
+int
+main ()
+{
+return ffwtf_malloc ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_link "$LINENO"; then :
+  ac_cv_lib_fftw3_ffwtf_malloc=yes
+else
+  ac_cv_lib_fftw3_ffwtf_malloc=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_fftw3_ffwtf_malloc" >&5
+$as_echo "$ac_cv_lib_fftw3_ffwtf_malloc" >&6; }
+if test "x$ac_cv_lib_fftw3_ffwtf_malloc" = xyes; then :
+  HAVE_LIBFFTW3=1
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: libfftw3 not available" >&5
+$as_echo "$as_me: WARNING: libfftw3 not available" >&2;}
+fi
+
+fi
+
+if test "$HAVE_LIBHACKRF" -eq 1 && test "$HAVE_LIBFFTW3"; then
+
+$as_echo "#define BUILD_HACKRF_SWEEP 1" >>confdefs.h
+
+    BUILD_HACKRF_SWEEP=1
+fi
+
 HAVE_LIBDW=0
 HAVE_LIBBFD=0
 
@@ -10970,6 +11106,13 @@ elif test "$linux" != "yes"; then
 	echo "n/a (only Linux)"
 else
 	echo "no (will not be able to control NetworkManager)";
+fi
+
+printf "       HackRF spectrum: "
+if test "$BUILD_HACKRF_SWEEP" -eq 1; then
+	echo "yes (libhackrf and libfftw3 present)";
+else
+	echo "no (missing libhackrf or libfftw3)";
 fi
 
 printf "        Built-in Debug: "
